#NDK_TOOLCHAIN_VERSION=clang3.3
NDK_TOOLCHAIN_VERSION := 4.8

APP_OPTIM := release
APP_CFLAGS += -DNDEBUG=1
APP_CFLAGS += -D_NDEBUG=1
APP_CPPFLAGS += -std=c++11
APP_CPPFLAGS += -DNDEBUG=1
APP_CPPFLAGS += -D_NDEBUG=1
APP_CPPFLAGS += -frtti
APP_CPPFLAGS += -fexceptions
APP_STL := gnustl_static
APP_ABI := armeabi-v7a
APP_PLATFORM := android-14
